# Generated by Django 4.0.3 on 2022-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Natural and pure', max_length=5000),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='https://c.ndtvimg.com/2019-04/dl9g6gn8_bananas_625x300_11_April_19.jpg', max_length=2083),
        ),
    ]
